# Generated by Django 5.0.6 on 2024-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=36, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_data', models.JSONField()),
                ('event_issuer', models.CharField(max_length=14)),
                ('event_signer', models.CharField(max_length=14)),
                ('status_code', models.IntegerField(null=True)),
                ('status_description', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_log',
            },
        ),
    ]
