# Generated by Django 5.0.3 on 2024-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('cpf', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('regiao', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes_financeiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesFinanceiroReembolsos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes_financeiro_reembolsos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesFinanceiroValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.IntegerField(blank=True, null=True)),
                ('convenio_farmacia', models.FloatField(blank=True, null=True)),
                ('adiant_salarial', models.FloatField(blank=True, null=True)),
                ('numero_empregados', models.IntegerField(blank=True, null=True)),
                ('numero_estagiarios', models.IntegerField(blank=True, null=True)),
                ('trabalhando', models.IntegerField(blank=True, null=True)),
                ('salario_contri_empregados', models.FloatField(blank=True, null=True)),
                ('salario_contri_contribuintes', models.FloatField(blank=True, null=True)),
                ('soma_salarios_provdt', models.FloatField(blank=True, null=True)),
                ('inss', models.FloatField(blank=True, null=True)),
                ('fgts', models.FloatField(blank=True, null=True)),
                ('irrf', models.FloatField(blank=True, null=True)),
                ('salarios_pagar', models.FloatField(blank=True, null=True)),
                ('vale_transporte', models.FloatField(blank=True, null=True)),
                ('assinat_eletronica', models.FloatField(blank=True, null=True)),
                ('vale_refeicao', models.FloatField(blank=True, null=True)),
                ('mensal_ponto_elet', models.FloatField(blank=True, null=True)),
                ('saude_seguranca_trabalho', models.FloatField(blank=True, null=True)),
                ('percentual_human', models.FloatField(blank=True, null=True)),
                ('economia_mensal', models.FloatField(blank=True, null=True)),
                ('economia_formal', models.FloatField(blank=True, null=True)),
                ('total_fatura', models.FloatField(blank=True, null=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('anexo_enviado', models.IntegerField()),
                ('relatorio_enviado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes_financeiro_valores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(max_length=64)),
                ('rg', models.CharField(blank=True, max_length=8, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('setor', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Robos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('execucoes', models.IntegerField(blank=True, null=True)),
                ('ultima_execucao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'robos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(max_length=64)),
                ('telefone_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('setor', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitacoes_cadastro',
                'managed': False,
            },
        ),
    ]
