# Generated by Django 5.0.3 on 2024-04-09 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('cpf', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('regiao', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes_financeiro',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('FLOAT', 'FLOAT'), ('BOOLEAN', 'BOOLEAN'), ('INTEGER', 'INTEGER'), ('DATE', 'DATE'), ('TEXT', 'TEXT')], default='TEXT', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parametros',
            },
        ),
        migrations.CreateModel(
            name='Robos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('execucoes', models.IntegerField(blank=True, null=True)),
                ('ultima_execucao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'robos',
            },
        ),
        migrations.CreateModel(
            name='ClientesFinanceiroReembolsos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='human_app.clientesfinanceiro')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes_financeiro_reembolsos',
            },
        ),
        migrations.CreateModel(
            name='ClientesFinanceiroValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='human_app.clientesfinanceiro')),
                ('cod_empresa', models.IntegerField(blank=True, null=True)),
                ('convenio_farmacia', models.FloatField(blank=True, null=True)),
                ('adiant_salarial', models.FloatField(blank=True, null=True)),
                ('numero_empregados', models.IntegerField(blank=True, null=True)),
                ('numero_estagiarios', models.IntegerField(blank=True, null=True)),
                ('trabalhando', models.IntegerField(blank=True, null=True)),
                ('salario_contri_empregados', models.FloatField(blank=True, null=True)),
                ('salario_contri_contribuintes', models.FloatField(blank=True, null=True)),
                ('soma_salarios_provdt', models.FloatField(blank=True, null=True)),
                ('inss', models.FloatField(blank=True, null=True)),
                ('fgts', models.FloatField(blank=True, null=True)),
                ('irrf', models.FloatField(blank=True, null=True)),
                ('salarios_pagar', models.FloatField(blank=True, null=True)),
                ('vale_transporte', models.FloatField(blank=True, null=True)),
                ('assinat_eletronica', models.FloatField(blank=True, null=True)),
                ('vale_refeicao', models.FloatField(blank=True, null=True)),
                ('mensal_ponto_elet', models.FloatField(blank=True, null=True)),
                ('saude_seguranca_trabalho', models.FloatField(blank=True, null=True)),
                ('percentual_human', models.FloatField(blank=True, null=True)),
                ('economia_mensal', models.FloatField(blank=True, null=True)),
                ('economia_formal', models.FloatField(blank=True, null=True)),
                ('total_fatura', models.FloatField(blank=True, null=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('anexo_enviado', models.IntegerField(default=0)),
                ('relatorio_enviado', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes_financeiro_valores',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rg', models.CharField(blank=True, max_length=8, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='RobosParametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='human_app.robos')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robos', to='human_app.parametros')),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'robos_parametros',
            },
        ),
        migrations.CreateModel(
            name='Rotinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='human_app.robos')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rotinas',
            },
        ),
    ]
