# Generated by Django 5.0.3 on 2024-03-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('DATE', 'DATE'), ('TEXT', 'TEXT'), ('FLOAT', 'FLOAT'), ('BOOLEAN', 'BOOLEAN'), ('INTEGER', 'INTEGER')], default='TEXT', max_length=255),
        ),
        migrations.CreateModel(
            name='Rotinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='human_app.robos')),
            ],
            options={
                'db_table': 'rotinas',
            },
        ),
    ]
