# Generated by Django 5.0.3 on 2024-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesfinanceirovalores',
            name='anexo_enviado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientesfinanceirovalores',
            name='relatorio_enviado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('BOOLEAN', 'BOOLEAN'), ('TEXT', 'TEXT'), ('FLOAT', 'FLOAT'), ('INTEGER', 'INTEGER'), ('DATE', 'DATE')], default='TEXT', max_length=255),
        ),
    ]
