# Generated by Django 5.0.3 on 2024-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='situacao',
            field=models.CharField(default='INATIVO', max_length=100),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('TEXT', 'TEXT'), ('DATE', 'DATE'), ('INTEGER', 'INTEGER'), ('BOOLEAN', 'BOOLEAN')], default='TEXT', max_length=255),
        ),
    ]
