# Generated by Django 5.0.3 on 2024-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0002_funcionarios_situacao_alter_parametros_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesfinanceiro',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('INTEGER', 'INTEGER'), ('FLOAT', 'FLOAT'), ('TEXT', 'TEXT'), ('DATE', 'DATE'), ('BOOLEAN', 'BOOLEAN')], default='TEXT', max_length=255),
        ),
    ]
