# Generated by Django 5.0.3 on 2024-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0003_clientesfinanceiro_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesfinanceiro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('INTEGER', 'INTEGER'), ('BOOLEAN', 'BOOLEAN'), ('TEXT', 'TEXT'), ('DATE', 'DATE')], default='TEXT', max_length=255),
        ),
    ]
