# Generated by Django 5.0.3 on 2024-06-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0004_clientesfinanceiro_is_active_alter_parametros_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('INTEGER', 'INTEGER'), ('DATE', 'DATE'), ('BOOLEAN', 'BOOLEAN'), ('TEXT', 'TEXT'), ('FLOAT', 'FLOAT')], default='TEXT', max_length=255),
        ),
        migrations.CreateModel(
            name='ClientesFinanceiroFolhaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado', models.BooleanField(default=False)),
                ('colaborador', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folha_ponto', to='human_app.clientesfinanceiro')),
            ],
            options={
                'db_table': 'clientes_financeiro_folha_ponto',
            },
        ),
    ]
