# Generated by Django 5.0.7 on 2024-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0002_alter_parametros_tipo_passwordresettokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesfinanceirovalores',
            name='seguro_estagio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('TEXT', 'TEXT'), ('INTEGER', 'INTEGER'), ('BOOLEAN', 'BOOLEAN'), ('DATE', 'DATE')], default='TEXT', max_length=255),
        ),
    ]
