# Generated by Django 5.0.6 on 2024-07-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0002_alter_parametros_tipo_passwordresettokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='tipo',
            field=models.CharField(choices=[('INTEGER', 'INTEGER'), ('DATE', 'DATE'), ('CENTRO_DE_CUSTO', 'CENTRO_DE_CUSTO'), ('TEXT', 'TEXT'), ('SELECT', 'SELECT'), ('BOOLEAN', 'BOOLEAN'), ('FLOAT', 'FLOAT')], default='TEXT', max_length=255),
        ),
        migrations.CreateModel(
            name='SelectOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_options', to='human_app.parametros')),
            ],
            options={
                'db_table': 'select_options',
            },
        ),
    ]
